prod:
  apt:
    - build-essential
    - mariadb-client
    - mongo-tools
    - php-cli
    - php-curl
    - php-json
    - php-mcrypt
    - php-mongodb
    - php-mysql
    - php-xml
    - zip

  pip:
    - mongoengine
    - pymongo
    - SQLAlchemy
